In [87]:
import warnings
warnings.filterwarnings("ignore")

In [88]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn import preprocessing 
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score, confusion_matrix

In [89]:
df = pd.read_csv("features_30_sec.csv")

In [90]:
df.drop("filename", axis = 1, inplace=True)

In [91]:
df.head()

length  chroma_stft_mean  chroma_stft_var  rms_mean   rms_var  \
0  661794          0.350088         0.088757  0.130228  0.002827   
1  661794          0.340914         0.094980  0.095948  0.002373   
2  661794          0.363637         0.085275  0.175570  0.002746   
3  661794          0.404785         0.093999  0.141093  0.006346   
4  661794          0.308526         0.087841  0.091529  0.002303   

   spectral_centroid_mean  spectral_centroid_var  spectral_bandwidth_mean  \
0             1784.165850          129774.064525              2002.449060   
1             1530.176679          375850.073649              2039.036516   
2             1552.811865          156467.643368              1747.702312   
3             1070.106615          184355.942417              1596.412872   
4             1835.004266          343399.939274              1748.172116   

   spectral_bandwidth_var  rolloff_mean  ...  mfcc16_var  mfcc17_mean  \
0            85882.761315   3805.839606  ...   52.420910    -1.690215   
1           213843.755497   3550.522098  ...   55.356403    -0.731125   
2            76254.192257   3042.260232  ...   40.598766    -7.729093   
3           166441.494769   2184.745799  ...   44.427753    -3.319597   
4            88445.209036   3579.757627  ...   86.099236    -5.454034   

   mfcc17_var  mfcc18_mean  mfcc18_var  mfcc19_mean  mfcc19_var  mfcc20_mean  \
0   36.524071    -0.408979   41.597103    -2.303523   55.062923     1.221291   
1   60.314529     0.295073   48.120598    -0.283518   51.106190     0.531217   
2   47.639427    -1.816407   52.382141    -3.439720   46.639660    -2.231258   
3   50.206673     0.636965   37.319130    -0.619121   37.259739    -3.407448   
4   75.269707    -0.916874   53.613918    -4.404827   62.910812   -11.703234   

   mfcc20_var  label  
0   46.936035  blues  
1   45.786282  blues  
2   30.573025  blues  
3   31.949339  blues  
4   55.195160  blues  

[5 rows x 59 columns]

In [92]:
df.shape

(1000, 59)

In [93]:
X = df.drop("label", axis = 1)
y = df["label"]

In [94]:
label_encoder = preprocessing.LabelEncoder() 
y = label_encoder.fit_transform(y) 

In [95]:
len(y)

1000

In [96]:
X_train, y_train, X_test, y_test = train_test_split(X, y, test_size=0.3, random_state=42, stratify = y)

# Gradient boost

In [97]:
from xgboost import XGBClassifier

In [98]:
model  = XGBClassifier(learning_rate = 0.01)

In [99]:
model.fit(X_train, X_test)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=0.01, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=None, n_jobs=None,
              num_parallel_tree=None, objective='multi:softprob', ...)

In [100]:
y_pred =  model.predict(y_train)
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
print("Accuracy:", accuracy)
print("Confusion Matrix:\n", conf_matrix)

Accuracy: 0.71
Confusion Matrix:
 [[18  0  2  0  2  2  1  0  4  1]
 [ 0 28  0  0  0  2  0  0  0  0]
 [ 3  0 20  1  0  4  0  0  1  1]
 [ 0  0  1 17  5  0  1  1  1  4]
 [ 0  0  1  2 22  0  1  0  1  3]
 [ 1  3  0  0  0 23  0  0  0  3]
 [ 0  0  0  2  0  1 25  0  1  1]
 [ 0  0  0  1  1  0  0 27  1  0]
 [ 0  0  1  2  0  0  0  6 20  1]
 [ 5  0  5  2  1  3  0  0  1 13]]


# Ada boost

In [101]:
from sklearn.ensemble import AdaBoostClassifier

In [102]:
ada_model = AdaBoostClassifier(learning_rate=0.01, random_state=42)

In [103]:
ada_model.fit(X_train, X_test)

AdaBoostClassifier(learning_rate=0.01, random_state=42)

In [104]:
y_pred = ada_model.predict(y_train)
print(accuracy_score(y_test, y_pred))

0.32


In [110]:
y_train

length  chroma_stft_mean  chroma_stft_var  rms_mean   rms_var  \
877  661504          0.395407         0.090621  0.116579  0.001520   
572  661794          0.250492         0.090480  0.110509  0.003491   
717  661504          0.435302         0.082635  0.143163  0.001065   
536  661794          0.322393         0.086365  0.080559  0.001165   
898  661504          0.410039         0.088842  0.139203  0.002202   
..      ...               ...              ...       ...       ...   
580  661794          0.370623         0.080463  0.075741  0.000366   
71   661794          0.305175         0.080065  0.120560  0.000325   
267  661794          0.321170         0.087852  0.055436  0.001231   
32   661794          0.276245         0.097367  0.101321  0.003951   
305  667920          0.448050         0.081806  0.206921  0.002887   

     spectral_centroid_mean  spectral_centroid_var  spectral_bandwidth_mean  \
877             1777.839586          330193.868576              2173.800933   
572             1336.153705           79907.295110              1554.249504   
717             2789.486477          373290.877657              2795.819855   
536             1481.568587          283211.662057              1412.025522   
898             2026.298986          575184.204476              2398.102837   
..                      ...                    ...                      ...   
580             3029.382383          215849.559866              2829.048804   
71              2428.928767           97719.368632              2286.710780   
267              857.638582          285170.859067              1238.029736   
32              1309.382408          756062.612347              1883.042903   
305             2722.744188          432474.935900              2569.340181   

     spectral_bandwidth_var  rolloff_mean  ...  mfcc16_mean  mfcc16_var  \
877           151560.984240   3821.177641  ...    -0.659431   37.083878   
572            37204.779247   2751.820122  ...    -1.451717  114.914856   
717           173281.566427   6113.356305  ...    -1.592633   37.034470   
536            55694.215657   2657.352145  ...    -6.402775   56.119350   
898           155401.937825   4462.743857  ...     0.295531   46.436260   
..                      ...           ...  ...          ...         ...   
580            64688.064353   6201.978842  ...    -1.190416   45.215237   
71             24997.757809   5064.932456  ...     6.537729   39.875996   
267           170818.132853   1443.765464  ...    -4.539808   43.379448   
32            284143.663735   2763.186256  ...   -15.693844   54.529968   
305            88645.239090   5471.916925  ...    -0.909492   42.392498   

     mfcc17_mean  mfcc17_var  mfcc18_mean  mfcc18_var  mfcc19_mean  \
877    -6.973977   55.756996    -2.430766   28.646009    -1.181231   
572     0.785720   65.228500    -0.403668   65.393135    -2.340947   
717     2.626786   32.076851     2.423898   42.317574     4.018723   
536    -2.889749   67.117867    -4.858112   60.748592    -5.886781   
898    -2.340442   40.343788     0.378325   50.873978     0.912167   
..           ...         ...          ...         ...          ...   
580    -1.064694   80.246048    -6.278792   76.546310    -5.385146   
71    -10.848482   36.344803     3.321702   41.157864    -6.186610   
267    -1.049614   64.151474    -4.595655   66.038048    -2.867130   
32    -10.957293   61.384270   -10.879780   45.184685   -18.501955   
305    -0.991282   67.083115    -3.463100   78.206863    -0.959025   

     mfcc19_var  mfcc20_mean  mfcc20_var  
877   27.497952    -3.811273   35.752388  
572   74.813179    -2.012356   70.788467  
717   39.560402     3.907003   44.817955  
536  104.076965    -9.120353  101.487358  
898   45.105530    -0.442557   79.085022  
..          ...          ...         ...  
580   64.969704    -4.865997   82.284782  
71    42.471439     3.005219   40.276005  
267   42.453922    -2.230965   45.933929  
32    55.886143   -19.117844   75.344734  


# Scaling

In [114]:
scaler = preprocessing.StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
y_train_scaled = scaler.transform(y_train)

In [113]:
model.fit(X_train_scaled, X_test)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=0.01, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=None, n_jobs=None,
              num_parallel_tree=None, objective='multi:softprob', ...)

In [115]:
y_pred = model.predict(y_train_scaled)
accuracy_score(y_pred, y_test)

0.71

In [116]:
ada_model.fit(X_train_scaled, X_test)

AdaBoostClassifier(learning_rate=0.01, random_state=42)

In [117]:
y_pred = ada_model.predict(y_train_scaled)
accuracy_score(y_pred, y_test)

0.32

In [118]:
y_train_scaled

array([[-2.91160042e-01,  2.17922367e-01,  5.50695157e-01, ...,
        -1.02134800e+00, -6.89670746e-01, -7.36283309e-01],
       [-1.40114092e-01, -1.56900217e+00,  5.32416389e-01, ...,
         2.26550274e-01, -2.33510319e-01, -1.90665285e-04],
       [-2.91160042e-01,  7.09869414e-01, -4.90524307e-01, ...,
        -7.03211287e-01,  1.26749131e+00, -5.45819727e-01],
       ...,
       [-1.40114092e-01, -6.97480042e-01,  1.89720580e-01, ...,
        -6.26897186e-01, -2.88943943e-01, -5.22373594e-01],
       [-1.40114092e-01, -1.25144584e+00,  1.43034726e+00, ...,
        -2.72633968e-01, -4.57103460e+00,  9.55344992e-02],
       [ 3.05060138e+00,  8.67058012e-01, -5.98546424e-01, ...,
         6.79591738e-03,  2.79163749e-01,  4.14642371e-01]])